# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ca18b94b053fc7bac5d45a57562fb150"
name = "SmartPriceBot"
handle = "smartpricebot"
application_url = "https://entry-driving-wife-guards.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://entry-driving-wife-guards.trycloudflare.com/auth/callback", "https://entry-driving-wife-guards.trycloudflare.com/auth/shopify/callback", "https://entry-driving-wife-guards.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
